### ISSUE TITLE
Sharing state between popup and content

### ISSUE THREAD

**Issue by mallowigi** [PlasmoHQ/storage#20]
Hi, I'm pretty new with the framework. I loved it but when it comes to actually use it, I stumbled upon a few issues that prevent me to do what I want, so I'd appreciate the help.

For my case, I have a popup.tsx and a content.tsx UI, which share the same settings. I tried to follow the examples `with-storage` to make sure I'm doing it wrong. Alas, it gives me inconsistent results: the settings persisted inside the popup and the settings inside the content are completely different!

After checking I saw that they are saved in the popup's localstorage (even though I specified the area to be `sync`), and the content's settings are saved in... the current website localstorage, making it useless since it would differ from page to page.

The examples didn't reflect that use case, so I'd appreciate if someone could help.

**Comment by louisgv** [comment]
> After checking I saw that they are saved in the popup's localstorage (even though I specified the area to be sync), and the content's settings are saved in... the current website localstorage, making it useless since it would differ from page to page.

So the `localstorage` usage is largely for "mirroring" the state with the target site. The source of truth is actually `chrome.storage`

> the settings persisted inside the popup and the settings inside the content are completely different

Which entry initiates the first default write? As long as the default are similar across your hook usage, they should "sync" on chrome's storage listener.

**Comment by mallowigi** [comment]
Ok your comment make me realize that I needed to add 
```
"permissions": [
    "storage"
  ],
```
to the manifest, although this [link](https://docs.plasmo.com/framework-api/storage#preventing-data-from-being-mirrored-into-localstorage) specified that it would be added automatically. By doing so I am now seeing the values being synced.

This looks like solved then, however I would suggest to update the documentation so that other people wouldn't fall in this issue.

**Comment by ColdSauce** [comment]
Interesting. Glad you got that taken care of. That looks to be a bug as those permissions should have been added automatically. So rather than updating the documentation, we'll look into fixing the bug.
