### ISSUE TITLE
Not Working on Chrome91

### ISSUE THREAD

**Issue by uinz** [PlasmoHQ/storage#26]
https://github.com/PlasmoHQ/storage/blob/main/src/index.ts#L157

`chrome.storage.local` on Chrome91 does not return a Promise.

should use callback

<img width="361" alt="image" src="https://user-images.githubusercontent.com/12208108/225249822-409f68a3-a9f3-406b-be4b-cd0fb13208f9.png">

**Comment by louisgv** [comment]
@uinz thanks for the bug report - can you try https://github.com/PlasmoHQ/storage/releases/tag/v1.3.0
