### ISSUE TITLE
Not working with Firefox since v1.1.0

### ISSUE THREAD

**Issue by Curetix** [PlasmoHQ/storage#27]
I'm using the React useStorage hook, like this:

```typescript
const extensionLocalStorage = new Storage({
  area: "local",
});

// ...

const [token] = useStorage<string>(
  {
    key: StorageKey.ApiToken,
    instance: extensionLocalStorage,
  },
  null,
);
```

When I update this module to v1.1.0 (a531a67) or above, it breaks my extension on Firefox:

![firefox_RKtuGv4zDd](https://user-images.githubusercontent.com/15160542/225578241-5a80a3fc-bef0-4e60-b8a1-97eb15ff9298.png)

It works fine with older versions. Was Firefox support intentionally removed?

**Comment by louisgv** [comment]
@Curetix thanks for the bug report - can you try out https://github.com/PlasmoHQ/storage/releases/tag/v1.3.0

**Comment by Curetix** [comment]
> @Curetix thanks for the bug report - can you try out https://github.com/PlasmoHQ/storage/releases/tag/v1.3.0

Thank you, that fixed it!

**Comment by erensertkaya** [comment]
How this library working in firefox or safari ? Is chrome.storage available for other browsers or this library using their storage api (i don't know if they have) ?

**Comment by Curetix** [comment]
> How this library working in firefox or safari ? Is chrome.storage available for other browsers or this library using their storage api (i don't know if they have) ?

The library chooses either `browser.storage` or `chrome.storage`, whichever is available ([src/index.tsx](https://github.com/PlasmoHQ/storage/blob/main/src/index.ts#L79)). Alternatively it falls back to localStorage I believe.

**Comment by erensertkaya** [comment]
> > How this library working in firefox or safari ? Is chrome.storage available for other browsers or this library using their storage api (i don't know if they have) ?
> 
> The library chooses either `browser.storage` or `chrome.storage`, whichever is available ([src/index.tsx](https://github.com/PlasmoHQ/storage/blob/main/src/index.ts#L79)). Alternatively it falls back to localStorage I believe.

If it's falls back to localStorage can it sync data between popup.tsx and content scripts ?
