### ISSUE TITLE
storage.delete does not seem to use Namespace causing entries not to be deleted.

### ISSUE THREAD

**Issue by shuntksh** [PlasmoHQ/storage#31]
Hi Plasmo team,

Not sure if this is an intended behavior but `Storage.prototype.remove` does not seem to consider the namespace, causing the workers that are using the namespace to fail to remove items with corresponding keys.

[src/index.ts](https://github.com/PlasmoHQ/storage/blob/590a06c64688d748a510754d97d165fa85f6dafb/src/index.ts#LL227C38-L227C38)
```typescript
await this.#primaryClient.remove(key)
```

Should this also use  `getNamespacedKey(key)` like get and set and have a rawRemove to remove entries directly?

```
  remove = async (key: string) => {
    const nsKey = getNamespacedKey(key)
    if (this.isCopied(nsKey)) {
      this.#secondaryClient?.removeItem(nsKey)
    }

    if (this.hasExtensionApi) {
      await this.#primaryClient.remove(nsKey)
    }
  }
```

I'd also be happy to work on a fix if this is unintended.

**Comment by louisgv** [comment]
@shuntksh Thank you so much for the issue! This is indeed unintended - the namespace feature was made quickly to experiment with the concept, and I indeed missed some of the places that need to incorporate the namespace along the way xD 

> I'd also be happy to work on a fix if this is unintended.

That would be greatly appreciated - thank you 🙏

**Comment by shuntksh** [comment]
Thanks, @louisgv! I've submitted a PR to the main repository. I'm not certain if that's the right approach, so please let me know if you'd prefer me to open a PR in this repository instead. Also, if there's anything I missed in the changes, just let me know!

Here's the link to the PR: https://github.com/PlasmoHQ/plasmo/pull/573

**Comment by shuntksh** [comment]
@louisgv  - Sorry I realized the original PR did not include the change I made to the sub-module, as it is pointing to the wrong repository. I reopened it as a draft PR in this repository. Let me know if this is the correct repository for the change.

Thanks!
