### ISSUE TITLE
TypeError: Error in invocation of storage.get(optional [string|array|object] keys, function callback): No matching signature.

### ISSUE THREAD

**Issue by goodspeed3** [PlasmoHQ/storage#33]
Hi,

I'm trying basic usage of Plasmo Storage API and getting this error.  Data is stored in popup session, but when I open pop-up again, storage seems to be reset.  Any ideas?

I've tried both the React Hooks API and the standard base Storage API.

`  const [checked, setChecked] = useStorage('checked', true);`

Error is triggered by running the above.  I must be missing something very simple.  Any ideas? Running Plasmo v.0.62.2 and  @plasmohq/storage 1.5.0

`hook.cjs:1 Uncaught (in promise) TypeError: Error in invocation of storage.get(optional [string|array|object] keys, function callback): No matching signature.
    at d.rawGet (hook.cjs:1:2608)
    at d.get (hook.cjs:1:4002)
    at hook.cjs:1:4500
    at commitHookEffectListMount (react-dom.development.js:23150:26)
    at commitPassiveMountOnFiber (react-dom.development.js:24926:13)
    at commitPassiveMountEffects_complete (react-dom.development.js:24891:9)
    at commitPassiveMountEffects_begin (react-dom.development.js:24878:7)
    at commitPassiveMountEffects (react-dom.development.js:24866:3)
    at flushPassiveEffectsImpl (react-dom.development.js:27039:3)
    at flushPassiveEffects (react-dom.development.js:26984:14)`

**Comment by louisgv** [comment]
> Data is stored in popup session, but when I open pop-up again, storage seems to be reset. Any ideas?

Did you try query those data in chrome.storage? the localStorage view is not the source of truth.

I'd recommend upgrading the framework as well, also which browser are you using?

**Comment by goodspeed3** [comment]
Yes, using chrome.storage.local works.  

Browser is Chrome 113.0.5672.92 (Official Build) (arm64)
Will try upgrading framework later.

**Comment by goodspeed3** [comment]
Ok upgraded framework to v0.70.1, same issue.

If I downgrade to v1.0.0, the error disappears.

**Comment by louisgv** [comment]
If you do `pnpm create plasmo --with-storage` and test that example project out, does it work or still error?

**Comment by i-CNNN** [comment]
manifest_version: 2

version: "@plasmohq/storage": "^1.6.0"

error: Error in invocation of storage.get(optional [string|array|object] keys, function callback): No matching signature.

**Comment by goodspeed3** [comment]
@louisgv yes, that works, but unfortunately I didn't start plasmo project with pnpm

**Comment by huangyemin** [comment]
i got the same problem when i use mv2

**Comment by adrienbrault** [comment]
I am running into the same issue with `--target=chrome-mv2`.

In my background page this does not work and triggers the error:
```
console.log( chrome.storage.local.get(null) )
```

While this works (callback argument required):
```
chrome.storage.local.get(null, result => console.log(result))
```
