### ISSUE TITLE
Make the key reactive in useStorage hook

### ISSUE THREAD

**Issue by fa-sharp** [PlasmoHQ/storage#36]
It looks like the key parameter of the useStorage hook isn't reactive, e.g. if you pass in a variable as the key, and then change that value later, it doesn't start reading from that new storage.

It seems this should be possible by simply adding the string key to the dependency array in this useEffect, in line 68. That way, if the key changes, the storage unmounts and remounts with the new key, resetting the render values in the process:

https://github.com/PlasmoHQ/storage/blob/6b58b8c1fe05575fae943728da00d375db325aa7/src/hook.ts#L41-L69

However, I'm not sure if this will cause issues or excess re-renders, so it would need some testing.

**Comment by louisgv** [comment]
Yeah we just need to unwatch it after the re-render. @fa-sharp wanna take a stab at a fix?

**Comment by fa-sharp** [comment]
Sure, I'll give it a try this week and make a PR!
