### ISSUE TITLE
missing tags / releases

### ISSUE THREAD

**Issue by DanielRuf** [PlasmoHQ/storage#43]
On GitHub there are releases and tags missing. For example 1.7.2:

https://github.com/PlasmoHQ/storage/blob/main/package.json#L3

https://github.com/PlasmoHQ/storage/releases

**Comment by louisgv** [comment]
The release for this package has been consolidated into the main framework release for the time being: https://github.com/PlasmoHQ/plasmo/releases/tag/v0.82.0

Since it's a bit of a chore to cut separate release across these repos :d...
