### ISSUE TITLE
Accessing storage from within a content UI script

### ISSUE THREAD

**Issue by svenefftinge** [PlasmoHQ/storage#44]
I want to access storage from a contents script. But because it runs in the context of the webpage `chrome.storage` is undefined. I also experimented with `localStorage` but also that seems to be not shared between the context options run in and my contents UI script does.
I've seen https://github.com/PlasmoHQ/examples/blob/main/with-storage/content.tsx and wonder why that works.

It seems like I'm missing something obvious here. Can you help?

**Comment by svenefftinge** [comment]
Turns out I used a bad configuration.
```
export const config: PlasmoCSConfig = {
  matches: ["<all_urls>"],
  world: "MAIN",
}
```

Removing the world property fixed the problem.

**Comment by HansBhatia** [comment]
I've been stuck on this for like an hour now... Why does removing (world: "Main") work?
